# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='journalism',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='quantified_self',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='smart_buildings',
            field=models.BooleanField(default=False),
        ),
    ]
