# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='row_num',
        ),
        migrations.AddField(
            model_name='event',
            name='serial',
            field=models.CharField(default='00:00:00:00:00:00:00', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='register',
            name='serial',
            field=models.CharField(default='00:00:00:00:00:00:00', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='register',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
