# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20160302_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='serial',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='register',
            name='serial',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
