# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20160302_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='serial',
        ),
        migrations.AddField(
            model_name='event',
            name='register',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.Register'),
        ),
    ]
