# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160105_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='special_needs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
