# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160105_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
